services:
  app:
    image: mysociety/la_distance:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /workspaces/la_distance      
    volumes:
      - ./:/workspaces/la_distance/